In [3]:
import tensorflow as tf
import numpy as np

def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [4]:
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons],dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()

In [3]:
import numpy as np

X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]]) # t = 0
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]]) # t = 1

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [4]:
Y0_val

array([[-0.41384122,  0.03566234,  0.44829905, -0.22302972,  0.93317813],
       [ 0.95809925,  0.81059384,  0.98533905,  0.8997494 ,  0.99902534],
       [ 0.99962038,  0.97676778,  0.99971372,  0.99646807,  0.99998623],
       [ 1.        ,  0.98940605,  0.96482176,  0.9978506 , -0.12188768]], dtype=float32)

In [11]:
reset_graph()

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1],
                                                dtype=tf.float32)
Y0, Y1 = output_seqs
Y2=states

In [12]:
init = tf.global_variables_initializer()


In [13]:
X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]])
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]])

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val,y2 = sess.run([Y0, Y1,Y2], feed_dict={X0: X0_batch, X1: X1_batch})

In [16]:
print(Y1_val)

[[-0.99959791 -0.99861729  0.98714626  0.99745679  1.        ]
 [-0.7247259   0.17925581  0.53362155 -0.65215266 -0.08035926]
 [-0.99574625 -0.968512    0.98747212  0.8410641   0.99999976]
 [-0.72859728 -0.27958852  0.80567396 -0.20588003  0.99954104]]


In [17]:
y2

array([[-0.99959791, -0.99861729,  0.98714626,  0.99745679,  1.        ],
       [-0.7247259 ,  0.17925581,  0.53362155, -0.65215266, -0.08035926],
       [-0.99574625, -0.968512  ,  0.98747212,  0.8410641 ,  0.99999976],
       [-0.72859728, -0.27958852,  0.80567396, -0.20588003,  0.99954104]], dtype=float32)

In [5]:
reset_graph()
n_steps = 2
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

In [6]:
init = tf.global_variables_initializer()

In [7]:

X_batch = np.array([
        [[0, 1, 2], [9, 8, 7]], # instance 1
        [[3, 4, 5], [0, 0, 0]], # instance 2
        [[6, 7, 8], [6, 5, 4]], # instance 3
        [[9, 0, 1], [3, 2, 1]], # instance 4
    ])

with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [8]:
print(outputs_val)

[[[ 0.90414059  0.49652389 -0.86023873  0.39286932 -0.30018687]
  [ 0.99999994  0.7632708  -1.          0.99888629 -0.7229408 ]]

 [[ 0.99988347  0.77785885 -0.99992859  0.9727248  -0.78886396]
  [ 0.44762579 -0.06916652 -0.51665425 -0.84579295  0.88807118]]

 [[ 0.99999988  0.91130519 -0.99999994  0.99912328 -0.9495424 ]
  [ 0.99998426  0.20443441 -0.99999785  0.94190496  0.35010839]]

 [[ 0.99490303  0.88642204 -0.99999571  0.99939185  0.97382313]
  [ 0.95951748  0.73643571 -0.99815828 -0.2651349   0.06432977]]]


In [9]:
reset_graph()

In [10]:
n_steps = 20
n_inputs = 1
n_neurons = 100
n_outputs = 1

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.float32, [None, n_steps, n_outputs])
cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu)
outputs, states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

In [11]:
reset_graph()

n_steps = 20
n_inputs = 1
n_neurons = 100
n_outputs = 1

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.float32, [None, n_steps, n_outputs])

In [12]:
cell = tf.contrib.rnn.OutputProjectionWrapper(
    tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu),
    output_size=n_outputs)


In [13]:
outputs, states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

In [14]:
learning_rate = 0.001

loss = tf.reduce_mean(tf.square(outputs - y)) # MSE
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

init = tf.global_variables_initializer()

In [15]:
saver = tf.train.Saver()

In [23]:
t_min, t_max = 0, 30
resolution = 0.1

def time_series(t):
    return t * np.sin(t) / 3 + 2 * np.sin(t*5)

def next_batch(batch_size, n_steps):
    t0 = np.random.rand(batch_size, 1) * (t_max - t_min - n_steps * resolution)
    Ts = t0 + np.arange(0., n_steps + 1) * resolution
    ys = time_series(Ts)
    return ys[:, :-1].reshape(-1, n_steps, 1), ys[:, 1:].reshape(-1, n_steps, 1)

In [24]:
n_iterations = 1500
batch_size = 50

with tf.Session() as sess:
    init.run()
    for iteration in range(n_iterations):
        X_batch, y_batch = next_batch(batch_size, n_steps)
        sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        if iteration % 100 == 0:
            mse = loss.eval(feed_dict={X: X_batch, y: y_batch})
            print(iteration, "\tMSE:", mse)
    
    saver.save(sess, "./my_time_series_model") # not shown in the book

0 	MSE: 17.3418
100 	MSE: 0.490782
200 	MSE: 0.179017
300 	MSE: 0.0759102
400 	MSE: 0.0595304
500 	MSE: 0.048711
600 	MSE: 0.0577073
700 	MSE: 0.0463169
800 	MSE: 0.0427499
900 	MSE: 0.046625
1000 	MSE: 0.0468868
1100 	MSE: 0.0422374
1200 	MSE: 0.0416583
1300 	MSE: 0.0483902
1400 	MSE: 0.0423835


In [10]:
x=np.ones((1,2,3))
print (np.array(x))

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [11]:
print(np.transpose(x,(1,0,2)))

[[[ 1.  1.  1.]]

 [[ 1.  1.  1.]]]


In [8]:
print(np.transpose(x,(2,0,1)))

[[[ 1.  1.]]

 [[ 1.  1.]]

 [[ 1.  1.]]]


In [16]:
print(np.reshape(x,[-1,3]))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
